### ISSUE TITLE
Like your design

### ISSUE THREAD

**Issue by ThomasHornschuh** [lxp32/lxp32-cpu#1]
Hi,
really nice and clean and still well optimized. I have currently started a fork where I adapted it to implement the Berkerly RISC-V ISA. Already implemented 90% of the RV32I subset. I just implemented a new decode stage, most other parts are need only slight adaptations. 
I just wan't to get in touch with you before I publish my fork.

**Comment by catharanthus** [comment]
Hello,

honestly, I'm surprised (in a good way) that my source code turned out to be useful for implementing another ISA. I worked in the opposite direction: came up with the pipeline architecture first, and then designed the instruction set that works well with this architecture.

Anyway, good luck and feel free to contact me if you have questions.
